# Generated by Django 3.2.12 on 2022-06-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='year',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Year'),
        ),
    ]
