# Generated by Django 3.2.12 on 2022-06-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citations', '0003_auto_20220629_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='title',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Title'),
        ),
    ]
