# Generated by Django 3.2.12 on 2022-06-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citations', '0004_alter_citation_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='volume',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Volume'),
        ),
    ]
