STANDARDIZATION_METHOD = [
    ("0", "Associação exata do título com base 'ISSN-Attrs'"),
    ("1", "Associação exata do título com mais de um código ISSN e desambiguação com base 'ISSN-Year-Volume'"),
    ("2", "Associação exata do título com mais de um código ISSN e desambiguação com base 'ISSN-Year-Volume' e volume inferido"),
    ("3", "Associação exata do título com mais de um código ISSN e desambiguação com base 'ISSN-Year-Volume-Artifitial'"),
    ("4", "Associação exata do título com mais de um código ISSN e desambiguação com base 'ISSN-Year-Volume-Artifitial' e volume inferido"),
    ("11", "Associação aproximada do título com um ou mais códigos ISSN e desambiguação com base 'ISSN-Year-Volume'"),
    ("12", "Associação aproximada do título com um ou mais códigos ISSN e desambiguação com base 'ISSN-Year-Volume' e volume inferido"),
    ("13", "Associação aproximada do título com um ou mais códigos ISSN e desambiguação com base 'ISSN-Year-Volume-Artifitial'"),
    ("14", "Associação aproximada do título com um ou mais códigos ISSN e desambiguação com base 'ISSN-Year-Volume-Artifitial' e volume inferido"),
    ("519", "Associação exata do título com mais de um código ISSN, mas sem desambiguação possível com base 'ISSN-Year-Volume'"),
    ("529", "Associação exata do título com mais de um código ISSN, mas sem desambiguação possível com base 'ISSN-Year-Volume' e volume inferido"),
    ("539", "Associação exata do título com mais de um código ISSN, mas sem desambiguação possível com base 'ISSN-Year-Volume-Artifitial'"),
    ("549", "Associação exata do título com mais de um código ISSN, mas sem desambiguação possível com base 'ISSN-Year-Volume-Artifitial' e volume inferido"),
    ("619", "Associação aproximada do título com um ou mais códigos ISSN, mas sem desambiguação possível com base 'ISSN-Year-Volume'"),
    ("629", "Associação aproximada do título com um ou mais códigos ISSN, mas sem desambiguação possível com base 'ISSN-Year-Volume' e volume inferido"),
    ("639", "Associação aproximada do título com um ou mais códigos ISSN, mas sem desambiguação possível com base 'ISSN-Year-Volume-Artifitial'"),
    ("649", "Associação aproximada do título com um ou mais códigos ISSN, mas sem desambiguação possível com base 'ISSN-Year-Volume-Artifitial' e volume inferido"),
    ("500", "Associação exata do título com mais de um códigos ISSN, mas nenhuma base foi capaz de decidir qual é o correto"),
    ("600", "Associação aproximada do título com um ou mais códigos ISSN, mas nenhuma base foi capaz de decidir qual é o correto"),
    ("70", "Título não foi encontrado na base 'ISSN-Attrs"),
    ("80", "Associação exata do título com mais de um código ISSN, mas não foi possível decidir qual é o correto, pois o ano informado é inválido"),
    ("81", "Associação aproximada do título com mais de um código ISSN, mas não foi possível decidir qual é o correto, pois o ano informado é inválido"),
    ("82", "O título não foi informado"),
    ("90", "Não foi realizada tentativa de associar o título a um código ISSN, pois existe código DOI"),
    ("91", "Não foi realizada tentativa de associar o título a um código ISSN de modo aproximado devido à indicação do usuário"),
]
